services:
  - type: web
    name: valhalla
    runtime: docker
    dockerfilePath: DockerfileProd
    healthCheckPath: /login
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: VALHALLA_DB
          property: host
      - key: DB_PORT
        fromDatabase:
          name: VALHALLA_DB
          property: port
      - key: DB_NAME
        fromDatabase:
          name: VALHALLA_DB
          property: database
      - key: DB_USER
        fromDatabase:
          name: VALHALLA_DB
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: VALHALLA_DB
          property: password

databases:
  - name: VALHALLA_DB
    plan: free
    databaseName: valhalla
